Project setup and DB creation
MarkoKermi/rentals_project-back-end pull request #1
Opened 2023-06-15 16:35 UTC by MarkoKermi

- [ ] In this PR I manage to create the following requirements: 

- setup the rails, with linters and Cors gem.
- Create the DB including the Users, Vespa and Reservation creation. 
- Setup the references between the tables in DB.
- Create the API folder and setup the controllers for Users, Vespas, Reservations and Authentication. 
- Create models.

2023-06-15 17:33 UTC, chepkok3 requested changes
Hi @MarkoKermi 

While you made a great effort in this task, unfortunately, I cannot proceed to review your task.

**Linter Errors.**
You have committed a task that has linter errors  [here](https://github.com/MarkoKermi/rentals_project-back-end/pull/1/commits/e3e1b1656f6c2f891021a6c42ccba9f3e7cfe36c)
Please submit a new one once the errors have been fixed. 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the Issue thread if something is not 100% clear.

Please, do not open a new Issue for re-reviews. You should use the same Issue submitted for the first review, either valid or invalid unless it is requested otherwise.

2023-06-16 11:02 UTC, chepkok3 reviewed
Hi [@MarkoKermi ](https://github.com/MarkoKermi)

Your task is complete! Great job for taking time to implement the changes🥇. There is nothing else to say other than... it's time to merge it 🍾🚢 : ship: Congratulations! 🎉💯🌟

- Good Points 👍
- Descriptive Pull Request✔️
- Design followed✔️
- Correct git-flow ✔️
- No linter errors✔️

Cheers..Happy coding!..and keep soaring higher! 💻 🍷 🚀
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 2 more limited reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-06-16 11:02 UTC, chepkok3 approved these changes

2023-06-16 12:28 UTC, Rudy-Menekam reviewed
Hi @MarkoKermi  ,

Your project is complete! There is nothing else to say other than... it's time to merge it :shipit:
Congratulations! +1

241275380-48fe06b1-eaf1-42c8-b0f6-7a1d5998444f

Optional suggestions
Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application.

Cheers, and Happy coding! 1st_place_medal

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-06-16 12:30 UTC, Rudy-Menekam approved these changes

2023-06-16 12:45 UTC, merged